---
resources:
  - name: master-branch
    type: git
    source:
      branch: master
      uri: git@github.com:MalpenZibo/rps.git
      private_key: ((repo-key))

jobs:
  - name: test
    plan:
      - get: master-branch
        params:
          depth: 1
        trigger: true
      - task: sbt-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: buildo/scala-sbt-alpine
              tag: 8u201_2.12.10_1.3.7
          inputs:
            - name: master-branch
          caches:
            - path: .sbt
            - path: .ivy2
          run:
            dir: master-branch
            path: sbt
            args:
              - -Dsbt.ivy.home=../.ivy2
              - -Dsbt.global.base=../.sbt/1.0
              - -Dsbt.boot.directory=../.sbt/boot
              - test
