---
resources:
  - name: master-branch
    type: git
    source:
      branch: master
      uri: git@github.com:MalpenZibo/rps.git
      private_key: ((repo-key))

jobs:
  - name: test
    plan:
      - get: master-branch
        trigger: true
      - task: sbt-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: buildo/scala-sbt-alpine
              tag: 8u201_2.12.11_1.3.9
          inputs:
            - name: master-branch
          run:
            dir: master-branch
            path: sbt
            args: [test]
